### ISSUE TITLE
Images are not being retrieved

### ISSUE THREAD

**Issue by Shiroifuyu** [KeziahMoselle/gelbooru-client#22]

**Comment by KeziahMoselle** [comment]
Steps to reproduce please ?

**Comment by Shiroifuyu** [comment]
Just installed 0.10.1 and whatever I do images won't appear
https://ame.s-ul.eu/BLiVyBTT.webm

**Comment by KeziahMoselle** [comment]
Okay so, the API is blocked due to an abuse : 
`<response success="false" reason="Search error: API disabled due to abuse."/>`
I have no idea how to fix that...

**Comment by KeziahMoselle** [comment]
According to Gelbooru's API page :
> API Basics You should never receive an error unless the server is overloaded or the search dies. In cases of the searcher breaking, you will receive a response success of "false" and a message stating "search down" or similiar.

So, yeah I can't do anything about that, Maybe add an error handler to catch, or do web scraping to get the images (fallback method).

**Comment by Shiroifuyu** [comment]
I investigated a little bit more and it's seems like a problem on Gelbooru end. Their servers got overloaded so they disabled the API temporarily.
Should be back in a couple hours.

**Comment by KeziahMoselle** [comment]
Oh ! Okay nice !
